services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root

  api:
    image: node:slim
    container_name: api
    volumes:
      - .:/api
    working_dir: /api
    depends_on:
      - postgres
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgresql://postgres:root@postgres:5432/ 
      PORT: 3000
    command: bash -c "npm install -g npm@9.7.1 && npm install && npx prisma migrate dev --name init && npm run dev:container"

    